"""Friendships

Revision ID: fecf967201a3
Revises: ef1ad8ca0ea6
Create Date: 2025-11-08 20:37:59.827971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fecf967201a3"
down_revision: Union[str, Sequence[str], None] = "ef1ad8ca0ea6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friendships",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id1", sa.BigInteger(), nullable=False),
        sa.Column("user_id2", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("user_id1 < user_id2"),
    )
    op.create_index(
        op.f("ix_friendships_user_id1"),
        "friendships",
        ["user_id1"],
        unique=False,
    )
    op.create_index(
        op.f("ix_friendships_user_id2"),
        "friendships",
        ["user_id2"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_friendships_user_id2"), table_name="friendships")
    op.drop_index(op.f("ix_friendships_user_id1"), table_name="friendships")
    op.drop_table("friendships")
    # ### end Alembic commands ###
